WIP: Added post method to registration
KogayIrina/todo-list pull request #9
Opened 2021-02-06 18:51 UTC by KogayIrina

2021-02-06 19:26 UTC, yurijmikhalevich commented on server/server.js
> +const salt = bcrypt.genSaltSync(10);
Соль должна быть постоянной между перезапусками приложения.

2021-02-08 09:42 UTC, KogayIrina commented on server/server.js
> +const salt = bcrypt.genSaltSync(10);
Исправила.

2021-02-08 10:30 UTC, yurijmikhalevich commented on server/server.js
> +  ctx.body = JSON.stringify();
Не надо возвращать клиенту юзера. Зачем? Хешированный пароль показывать в принципе плохая идея.

Надо либо ничего не возвращать, либо логинить юзера и устанавливать куку с сессией.

2021-02-08 10:31 UTC, yurijmikhalevich requested changes
Не надо возвращать клиенту хешированный пароль.

2021-02-08 10:59 UTC, KogayIrina commented on server/server.js
> +  ctx.body = JSON.stringify();
удалила строку.

2021-02-08 11:05 UTC, yurijmikhalevich approved these changes

2021-02-08 11:26 UTC, merged